# ??????????
spring.application.name=NoodleTrail
server.port=8080
server.address=172.20.10.3

debug=true

# ????????????????????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 1. ????? shaanxi_food_db ???????????????? shan?????
spring.datasource.url=jdbc:mysql://localhost:3306/shan?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
# 2. ?????????? 2023015801 ???????????? MySQL ????
spring.datasource.password=2023015801

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Jackson visibility to ensure fields are serialized even without Lombok
spring.jackson.visibility.field=any
spring.jackson.visibility.getter=public_only
spring.jackson.visibility.is-getter=public_only
# ???????????? MySQL ??? REPEATABLE_READ
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.transaction-isolation=TRANSACTION_REPEATABLE_READ

# Amap (Gaode) Map API config for check-in reverse geocoding
amap.key=96cd9b9cb1eb94681585bad6e0d784bc
amap.reverse-geocode-url=https://restapi.amap.com/v3/geocode/regeo
amap.radius=500
amap.extensions=all

# WeChat Mini Program config
wechat.miniapp.appid=wx0ac98f81e0ed6ad0
wechat.miniapp.secret=cad16ffea1c3e85044c25458d07b0c98
