/*
 Navicat Premium Dump SQL

 Source Server         : project
 Source Server Type    : MySQL
 Source Server Version : 80028 (8.0.28)
 Source Host           : localhost:3306
 Source Schema         : shan

 Target Server Type    : MySQL
 Target Server Version : 80028 (8.0.28)
 File Encoding         : 65001

 Date: 01/12/2025 21:04:48
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for shaanxi_intangible_heritage
-- ----------------------------
DROP TABLE IF EXISTS `shaanxi_intangible_heritage`;
CREATE TABLE `shaanxi_intangible_heritage`  (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '非遗项目名称',
  `category` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '所属种类（如：传统音乐、传统舞蹈等）',
  `historical_origin` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '历史渊源（约200字）',
  `content_introduction` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '内容介绍',
  `image_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '图片URL',
  `video_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '视频URL',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_category`(`category` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 41 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '陕西非物质文化遗产项目信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of shaanxi_intangible_heritage
-- ----------------------------
INSERT INTO `shaanxi_intangible_heritage` VALUES (1, '西安鼓乐', '传统音乐', '西安鼓乐源于唐代燕乐，距今已有1300多年历史，被誉为“中国古代交响乐”。它以鼓乐为主，融合了打击乐、吹管乐和弹弦乐等多种乐器，是流传在陕西西安城乡地区及沿终南山麓一带的大型综合性乐种。其乐谱采用独特的“工尺谱”和“半字谱”记谱法，完整保留了唐宋宫廷音乐的遗韵，具有极高的历史和文化价值。', '西安鼓乐分为僧、道、俗三派，曲目丰富，演奏形式多样，包括坐乐和行乐。其演奏风格庄重典雅，气势恢宏，旋律古朴悠扬，是研究中国古代音乐史的“活化石”。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/XiAnGuYue.png', 'https://www.youtube.com/watch?v=64yPiVRjbs8');
INSERT INTO `shaanxi_intangible_heritage` VALUES (2, '紫阳民歌', '传统音乐', '紫阳民歌是流传在陕西安康市紫阳县境内的传统民间歌曲总称，是陕南地区传统民歌中最具代表性的曲种。它起源于秦巴山区劳动人民的日常生活，形成于明清时期，并于2006年入选首批国家级非物质文化遗产名录。其曲调优美动听，语言形象生动，具有鲜明的地域特色。', '紫阳民歌分为号子、山歌、小调、社火歌曲、风俗歌曲、宗教歌曲、紫阳曲子和新民歌等八大类，整理存留曲目总数已达5000余首。其内容多反映当地的生产劳动、婚恋习俗、历史故事等，是研究陕南地区社会历史和民俗文化的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ZiYangMinGe.png', 'https://tv.cctv.com/2025/05/28/VIDEf9LmgJJ3JTU82ZMtIYbM250528.shtml');
INSERT INTO `shaanxi_intangible_heritage` VALUES (3, '陕北民歌', '传统音乐', '陕北民歌是流传于陕西省北部黄土高原地区的民歌，历史悠久，源远流长。它是在黄土高原特定的地理环境和历史文化背景下形成的，是陕北人民情感和生活的真实写照。其主要曲调包括信天游、小调、劳动号子等，以其高亢、粗犷、豪迈的风格而闻名。', '陕北民歌的代表曲目有《东方红》《兰花花》《走西口》等，其歌词多采用比兴手法，语言朴实无华，情感真挚热烈。它不仅是音乐艺术，更是陕北人民精神风貌和文化传统的集中体现，被誉为“黄土高原上的歌魂”。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ShanBeiMinGe.png', 'https://www.youtube.com/watch?v=RLlQO9uXLEs');
INSERT INTO `shaanxi_intangible_heritage` VALUES (4, '华阴老腔', '传统音乐', '华阴老腔，又称“老腔”，是流传于陕西省渭南市华阴市的一种古老民间戏曲，被誉为“黄土地上的摇滚”。它起源于明末清初，最初是当地皮影戏的伴奏音乐，后发展成为一种独特的说唱艺术。其唱腔高亢激昂，极富穿透力，具有强烈的地域特色。', '华阴老腔的表演形式独特，由五位艺人围坐一桌，手持板凳、木块等作为乐器，一人主唱，众人帮腔。其唱词内容多取材于历史故事和民间传说，以其粗犷豪迈、声震云霄的演唱风格，展现了关中人民坚韧不拔、乐观向上的精神。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HuaYinLaoQiang.png', 'https://www.youtube.com/watch?v=JIQVsUnAf1g');
INSERT INTO `shaanxi_intangible_heritage` VALUES (5, '汉调桄桄', '传统音乐', '汉调桄桄是流传于陕西省汉中地区的一种古老戏曲声腔，因其主要伴奏乐器“桄桄”而得名。它起源于明代，是在秦腔传入汉中后，与当地的民间音乐、方言相结合，逐渐演变形成。其唱腔高亢激越，曲调丰富，具有浓郁的巴蜀文化和秦腔艺术的融合特色。', '汉调桄桄的剧目多取材于历史演义和民间故事，表演风格粗犷豪放，动作幅度大，富有激情。它是研究秦腔声腔流变和地方戏曲发展的重要实例，也是陕南地区重要的文化遗产。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HanDiao.png', 'https://www.youtube.com/watch?v=5Q7x3v1f6wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (6, '安塞腰鼓', '传统舞蹈', '安塞腰鼓是流传于陕西省延安市安塞区的一种具有浓郁陕北地方特色的民间舞蹈。它起源于古代的军旅和祭祀活动，经过千百年的发展，逐渐演变为一种集舞蹈、武术、体操、打击乐为一体的综合性艺术形式。它以其磅礴的气势、豪迈的舞姿和激昂的鼓点而闻名。', '安塞腰鼓的表演场面宏大，鼓手们身着统一的服装，手持腰鼓，在激昂的鼓点中尽情挥洒。其动作刚劲有力，变化多端，节奏明快，富有感染力，充分展现了陕北人民粗犷豪放、热情奔放的性格。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/AnSaiYaoGu.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (7, '周至竹马', '传统舞蹈', '周至竹马是流传于陕西省西安市周至县的一种民间舞蹈，历史悠久，可追溯至唐代。它以竹子扎制成马的形状，表演者骑在竹马上，边舞边唱，模拟骑马奔驰的场景。它常在春节、元宵节等节日期间表演，以祈求风调雨顺、五谷丰登。', '周至竹马的表演形式活泼有趣，舞者身着戏服，头戴面具，在锣鼓丝竹的伴奏下，表演各种马术动作和故事情节。其舞蹈动作矫健优美，具有浓郁的乡土气息和戏曲色彩，是研究关中地区民间舞蹈的重要资料。', 'https://baike.baidu.com/item/%E5%91%A8%E8%87%B3%E7%ABhttps://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ZhouZhiZhuMa.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (8, '韩城行鼓', '传统舞蹈', '韩城行鼓是流传于陕西省渭南市韩城市的一种大型民间鼓乐舞蹈。它起源于古代的军阵和祭祀活动，后逐渐演变为一种民间娱乐形式。它以其独特的鼓点、激昂的节奏和宏大的场面而著称，是韩城地区重要的文化符号。', '韩城行鼓的表演队伍庞大，鼓手们身背大鼓，边走边击，气势磅礴。其鼓点变化丰富，节奏感强，舞姿刚劲有力，充满阳刚之美。它不仅是一种舞蹈，更是一种力量和精神的象征，展现了韩城人民豪迈奔放的性格。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HanChengXingGu.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (9, '横山老腰鼓', '传统舞蹈', '横山老腰鼓是流传于陕西省榆林市横山区的一种民间舞蹈，与安塞腰鼓同属陕北腰鼓系列，但风格略有不同。它起源于古代的军旅生活和祭祀活动，历史悠久。其特点是鼓点古朴、节奏缓慢、舞姿沉稳，更具历史的沧桑感。', '横山老腰鼓的表演形式庄重古朴，鼓手们动作沉稳有力，鼓点深沉厚重，仿佛在诉说着历史的变迁。它常在重大节日和庆典活动中表演，以其独特的艺术魅力，展现了陕北人民深沉内敛、坚韧不拔的民族精神。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HengShanLaoYaoGu.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (10, '秦汉战鼓', '传统舞蹈', '秦汉战鼓是流传于陕西省西安市及周边地区的一种民间鼓乐舞蹈，其历史可追溯到秦汉时期。它模拟古代战场上的战鼓声和军阵变化，以其雄壮的鼓点和威武的舞姿，展现了秦汉时期军队的雄风和气势。', '秦汉战鼓的表演场面壮观，鼓手们身着古代战袍，手持鼓槌，在震耳欲聋的鼓声中，表演各种战阵和搏击动作。其鼓点激昂，节奏紧凑，舞姿威武雄壮，具有强烈的历史感和艺术感染力，是研究秦汉军事文化的重要载体。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/QinHanZhanGu.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (11, '秦腔', '传统戏剧', '秦腔，又称“乱弹”，是中国最古老的戏曲剧种之一，起源于陕西、甘肃、宁夏、青海、新疆等地，尤以陕西为盛。它形成于秦代，发展于明清，以其高亢激越、慷慨悲凉的唱腔和丰富的剧目而被称为“百戏之祖”。秦腔的唱腔艺术对京剧、豫剧等剧种产生了深远影响。', '秦腔的表演艺术粗犷豪放，动作幅度大，特技丰富。其脸谱、服饰、道具等都具有鲜明的地域特色。秦腔剧目多取材于历史故事和民间传说，内容丰富，情节曲折，深受西北人民的喜爱。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/QinQiang.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (12, '碗碗腔', '传统戏剧', '碗碗腔是流传于陕西省渭南市、西安市等地的一种地方戏曲，因其主要伴奏乐器“碗碗”而得名。它起源于明末清初，是在当地民间小调和皮影戏音乐的基础上发展形成。其唱腔委婉细腻，曲调优美，具有浓郁的江南丝竹韵味。', '碗碗腔的表演风格清新典雅，以唱功见长，尤以旦角表演细腻传神。其剧目多以才子佳人、家庭伦理故事为主，唱腔柔美动听，深受关中地区人民的喜爱。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/WanWanQiang.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (13, '眉户', '传统戏剧', '眉户戏，又称“迷胡子”或“曲子戏”，是陕西省第二大地方剧种，主要流行于关中地区。它起源于明代，是在当地民间小调和曲艺的基础上发展形成。其唱腔婉转缠绵，曲调丰富，具有浓郁的乡土气息。', '眉户戏的表演风格朴实自然，生活气息浓厚。其剧目多取材于农村生活和民间故事，内容贴近百姓，语言通俗易懂。它是研究关中地区民间音乐和戏曲发展的重要资料。', 'https://baike.baidu.com/item/%E7%9Chttps://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/MeiHuXi.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (14, '华县皮影戏', '传统戏剧', '华县皮影戏，又称“灯影子”，起源于陕西省渭南市华州区（原华县），是中国皮影戏艺术中最具代表性的流派之一。它历史悠久，可追溯到西汉时期，被誉为“世界最早的电影”。其影人雕刻精美，唱腔以碗碗腔为主，表演细腻传神。', '华县皮影戏的表演形式独特，艺人在幕后操纵皮影人物，配合唱腔和音乐，讲述历史故事和民间传说。其影人雕刻技艺精湛，色彩鲜艳，具有极高的艺术价值。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HuaXianPiYingXi.png', 'https://www.youtube.com/watch?v=m54nFYrnij4');
INSERT INTO `shaanxi_intangible_heritage` VALUES (15, '汉调二簧', '传统戏剧', '汉调二簧是流传于陕西省汉中地区的一种地方戏曲，是京剧的主要声腔之一“二簧”的源头之一。它起源于清代，是在徽调、秦腔等声腔的基础上发展形成。其唱腔高亢激越，曲调丰富，具有浓郁的巴蜀文化和楚文化特色。', '汉调二簧的表演风格大气磅礴，以武戏见长，动作幅度大，特技丰富。其剧目多取材于历史演义和民间故事，是研究京剧声腔流变和地方戏曲发展的重要实例。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HanDiaoErHuang.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (16, '陕北说书', '曲艺', '陕北说书是流传于陕西省北部地区的一种民间说唱艺术，历史悠久，可追溯到唐代。它以陕北方言说唱历史故事和民间传说，形式多样，内容丰富，是陕北人民喜闻乐见的娱乐形式。', '陕北说书的表演形式简单，一人或两人说唱，手持三弦、板胡等乐器伴奏。其唱腔高亢激昂，节奏明快，语言幽默风趣，具有浓郁的乡土气息。它是研究陕北地区民间文学和曲艺发展的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ShanBeiShuoShu.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (17, '长安道情', '曲艺', '长安道情是流传于陕西省西安市及周边地区的一种民间说唱艺术，起源于唐代，是在道教音乐和民间小调的基础上发展形成。它以其独特的唱腔和丰富的曲目而著称，是关中地区重要的曲艺形式。', '长安道情的表演形式多样，一人或多人说唱，手持渔鼓、简板等乐器伴奏。其唱腔委婉细腻，曲调优美，内容多取材于历史故事、民间传说和劝善故事，具有浓郁的宗教色彩和地方特色。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ChangAnDaoQin.png', 'https://www.youtube.com/watch?v=1b-y7v0p2wQ');
INSERT INTO `shaanxi_intangible_heritage` VALUES (18, '陕西快板', '曲艺', '陕西快板是兴起于20世纪50年代并流行于关中地区的一种新型曲艺品种。它是在秦腔“数板”的基础上，吸收了山东快书、练子嘴、快板书的表演形式发展而来。它以竹板或鼓点等有节奏的语言表达，具有鲜明的时代特色。', '陕西快板的表演形式活泼有趣，一人或多人说唱，手持竹板或快板，节奏明快，语言幽默风趣。其内容多反映社会生活、时事新闻和道德伦理，深受关中地区人民的喜爱。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ShanXiKuaiBan.png', 'https://tv.cctv.com/2021/02/08/VIDE0WiA1GDsB3Hc5jtU92Qk210208.shtml');
INSERT INTO `shaanxi_intangible_heritage` VALUES (19, '镇巴渔鼓', '曲艺', '镇巴渔鼓是流传于陕西省汉中市镇巴县的一种传统民间曲艺曲种，因其主要伴奏乐器“渔鼓”而得名。它起源于清末民初，是在当地民间小调和说唱艺术的基础上发展形成。其唱腔独特，曲调优美，具有浓郁的巴蜀文化特色。', '镇巴渔鼓的表演形式简单，一人说唱，手持渔鼓和简板伴奏。其唱腔婉转细腻，曲调优美，内容多取材于历史故事和民间传说，是研究陕南地区民间音乐和曲艺发展的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ZhenBaYuGu.png', 'https://xczx.cctv.cn/2024/02/21/VIDEClDo9dMxZtgkkNubLYN1240221.shtml');
INSERT INTO `shaanxi_intangible_heritage` VALUES (20, '眉户曲子', '曲艺', '眉户曲子，俗称“户县曲子”，是流传于陕西省西安市鄠邑区的一种唱曲类曲艺形式，是国家级非物质文化遗产代表性项目。它是在眉户戏的唱腔基础上发展形成，以其独特的曲调和丰富的曲目而著称。', '眉户曲子的表演形式多样，一人或多人演唱，手持板胡、二胡等乐器伴奏。其唱腔婉转缠绵，曲调优美，内容多取材于民间故事和生活场景，具有浓郁的乡土气息。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/MeiHuQuZi.png', 'https://www.youtube.com/watch?v=ocCvfU0tyuk');
INSERT INTO `shaanxi_intangible_heritage` VALUES (21, '凤翔泥塑', '传统美术', '凤翔泥塑是流传于陕西省宝鸡市凤翔区的一种民间美术，当地人称“泥货”或“泥活儿”。它起源于先秦西周时期，已有3000多年的历史。其造型洗练夸张，装饰华美富繁，色彩艳丽喜庆，具有浓郁的乡土气息。', '凤翔泥塑的制作工艺独特，以当地的粘土为原料，经过制模、翻胚、合缝、粉白、彩绘、上光等十多道工序制作而成。其题材广泛，包括神话人物、历史故事、动物造型等，是研究中国民间美术和民俗文化的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/FengXiangNiSu.png', 'http://travel.cctv.com/2017/08/23/VIDEHIBCvjGziiyjs9rPtn0s170823.shtml');
INSERT INTO `shaanxi_intangible_heritage` VALUES (22, '华县皮影雕刻技艺', '传统美术', '华县皮影雕刻技艺是流传于陕西省渭南市华州区（原华县）的一种传统手工技艺，是华县皮影戏的重要组成部分。它起源于西汉时期，已有上千年历史。其雕刻技艺精湛，刀法细腻，线条流畅，具有极高的艺术价值。', '华县皮影雕刻以牛皮为原料，经过刮皮、雕刻、上色、缝合等二十多道工序制作而成。其雕刻手法独特，以“推皮运刀”为主，影人造型优美，人物个性特征鲜明，是研究中国皮影艺术和民间雕刻技艺的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HuaXianPiYingDiaoKe.png', 'https://www.youtube.com/watch?v=m54nFYrnij4');
INSERT INTO `shaanxi_intangible_heritage` VALUES (23, '凤翔木版年画', '传统美术', '凤翔木版年画是流传于陕西省宝鸡市凤翔区的一种传统民间木版年画，始于唐宋，盛于明清，已有五百余年历史。它以其独特的艺术风格和丰富的题材内容而著称，是中国四大木版年画之一。', '凤翔木版年画的制作工艺独特，全以手工雕版，土法印制，局部手绘染填，套上金银二色，色彩对比强烈，造型饱满夸张，保留了古版年画古朴自然的艺术风格。其题材广泛，包括门神、财神、戏曲故事等，是研究中国民间美术和民俗文化的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/FengXiangMuBanNianHua.png', 'https://www.bilibili.com/video/BV1Jt41157YG/');
INSERT INTO `shaanxi_intangible_heritage` VALUES (24, '户县农民画', '传统美术', '户县农民画是流传于陕西省西安市鄠邑区的一种民间绘画艺术，源于民间，是在当地剪纸、壁画、年画、刺绣等民间艺术基础上衍变而来。它以朴实的绘画语言，详尽而生动地记录了农村生产劳动的壮观场面和热烈活泼的节庆场景。', '户县农民画的特点是色彩浓烈，对比强烈，造型夸张，充满想象力。其作者多为当地农民，他们用画笔描绘自己的生活和梦想，展现了新时代农民的精神风貌和对美好生活的向往。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/HuXianNongMinHua.png', 'https://tv.cctv.com/v/v1/VIDE6sWuf887yjImwBjR7BiO090817.html');
INSERT INTO `shaanxi_intangible_heritage` VALUES (25, '旬邑唢呐', '传统美术', '旬邑唢呐艺术起源于陕西省旬邑县的一种地方唢呐艺术。迄今已有500多年的历史，源远流长，曲目繁多，原有曲目100余首，旋律优美，高亢激昂。多以婚丧嫁娶，助兴致衰，过寿乔迁，喜庆集会，节日庆典、助兴演出为主要活动。', '旬邑唢呐的表演形式多样，唢呐吹奏与舞蹈艺术相结合，广场表演相结合，编排出的百人表演、多人舞吹、双人演奏唢呐等形式，具有浓郁的乡土气息和地方特色。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/XunYiSuoNa.png', 'https://www.douyin.com/video/7300785125581770011');
INSERT INTO `shaanxi_intangible_heritage` VALUES (26, '陕西社火', '民俗', '陕西社火是流传于陕西省各地的一种大型民间庆祝活动，多在春节、元宵节期间举行。它起源于古代的祭祀活动，后逐渐演变为一种集歌舞、戏剧、杂技、造型艺术为一体的综合性民间艺术。', '陕西社火的种类繁多，包括高芯、血社火、马社火、背社火等，表演形式丰富多彩，场面宏大壮观。其表演内容多取材于历史故事和民间传说，以其独特的艺术魅力，展现了陕西人民热情奔放、乐观向上的精神。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/ShanXiSheHuo.png', 'https://www.youtube.com/watch?v=0UQa-oknLsE');
INSERT INTO `shaanxi_intangible_heritage` VALUES (27, '鄠邑北乡迎祭城隍民俗活动', '民俗', '鄠邑北乡迎祭城隍民俗活动是流传于陕西省西安市鄠邑区北部乡村的一种古老民俗活动，已有600多年的历史。它源于对城隍神的信仰，是当地人民祈求风调雨顺、国泰民安的重要仪式。', '迎祭城隍活动通常在春节期间举行，包括迎神、祭祀、游神等环节。活动场面宏大，队伍庞大，包括鼓乐、社火、竹马等多种民间艺术形式。它是研究关中地区民间信仰和民俗文化的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/EYiBeiXiangYinJi.png', 'https://www.douyin.com/video/7335706496543575336');
INSERT INTO `shaanxi_intangible_heritage` VALUES (28, '米脂婚俗', '民俗', '米脂婚俗是流传于陕西省榆林市米脂县的一种传统婚俗，具有浓郁的陕北地方特色。它是在古代“六礼”的基础上，结合当地的民间习俗发展形成，以其独特的仪式和热闹的场面而著称。', '米脂婚俗的流程复杂，包括说媒、定亲、迎亲、拜堂等环节。其中，“米脂闯王花轿”迎亲队伍最为著名，队伍中新郎官身披红袍，骑着高头大马，喜婆跟随其后，带领轿夫和秧歌队，场面热闹喜庆。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/MiZhiHunSu.png', 'https://www.youtube.com/watch?v=1Tk1EKvfrNE');
INSERT INTO `shaanxi_intangible_heritage` VALUES (29, '耀州窑陶瓷烧制技艺', '传统技艺', '耀州窑陶瓷烧制技艺是流传于陕西省铜川市的一种传统手工技艺，是中国陶瓷烧造技艺的“六大窑系”之一。它起源于唐代，宋代达到鼎盛，以其特有的宋代橄榄青釉及精湛的刻花技艺著称，被誉为“巧如范金，精比琢玉”。', '耀州窑的传统工艺主要体现在原料的采配、泥料的储备、手工拉坯、雕花、刻花、划花、贴花、印花，以及釉药的选配和敷施等。其烧制出的瓷器造型优美，釉色青翠，纹饰精美，具有极高的艺术价值。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/YaoZhouYaoTao.png', 'https://livechina.cctv.com/2024/01/29/VIDE512TM5UtrQR8xQd8MAsS240129.shtml');
INSERT INTO `shaanxi_intangible_heritage` VALUES (30, '凤翔木版年画技艺', '传统技艺', '凤翔木版年画技艺是流传于陕西省宝鸡市凤翔区的一种传统手工技艺，是凤翔木版年画的制作工艺。它始于唐宋，盛于明清，已有五百余年历史。它以其独特的艺术风格和丰富的题材内容而著称，是中国四大木版年画之一。', '凤翔木版年画的制作工艺独特，全以手工雕版，土法印制，局部手绘染填，套上金银二色，色彩对比强烈，造型饱满夸张，保留了古版年画古朴自然的艺术风格。其题材广泛，包括门神、财神、戏曲故事等，是研究中国民间美术和民俗文化的重要资料。', 'https://qiqjregvdczjxckgiqan.supabase.co/storage/v1/object/public/shaanxi_intangible_heritage/FengXiangMuBanNianHua.png', 'https://www.douyin.com/search/%E5%87%A4%E7%BF%94%E6%9C%A8%E7%89%88%E5%B9%B4%E7%94%BB%E5%8D%B0%E5%88%B6%E8%A7%86%E9%A2%91');

SET FOREIGN_KEY_CHECKS = 1;
